//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DishOrderSystemDAL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class DishOrderEntities : DbContext, IDishOrderModelContainer
    {
        public DishOrderEntities()
            : base("name=DishOrderEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual IDbSet<Dish_DishType> Dish_DishType { get; set; }
        public virtual IDbSet<Dish_TimeOfDay> Dish_TimeOfDay { get; set; }
        public virtual IDbSet<Dish> Dishes { get; set; }
        public virtual IDbSet<DishType> DishTypes { get; set; }
        public virtual IDbSet<TimeOfDay> TimeOfDays { get; set; }
    }
}
