//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DishOrderSystemDAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dish_DishType
    {
        public int Id { get; set; }
        public int DishId { get; set; }
        public int DishTypeId { get; set; }
    
        public virtual Dish Dish { get; set; }
        public virtual DishType DishType { get; set; }
    }
}
